version: '3.4'

services:
  my.data.api:
    image: ${DOCKER_REGISTRY-}mydataapi
    build:
      context: .
      dockerfile: my.data.api/Dockerfile

  my.data.bandwidth:
    image: ${DOCKER_REGISTRY-}mydatabandwidth
    build:
      context: .
      dockerfile: my.data.bandwidth/Dockerfile

